cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --time={resources.time}
    --partition={resources.partition}
    --qos={resources.qos}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --gres={resources.gres}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --parsable
cluster-status:
  status-sacct.sh
default-resources:
  - partition=physical
  - qos=normal
  - mem_mb=1000
  - time=5
  - gres=''
restart-times: 0
max-jobs-per-second: 100
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-singularity: True
singularity-args: "-B $PWD,$TMPDIR --nv -H $(mktemp -d) --pwd $PWD --containall --cleanenv --writable-tmpfs"
